### ISSUE TITLE
Complete first release tasks

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/api-utils-python#3]
I believe the things that would be nice for first release include

- [x] Being able to specify scopes and apis manually
- [x] Being able to specify limits manually
- [x] A basic dictionary that contains the api calls, limits and scopes we're using
- [x] Support for PUT requests #5 
- [x] Support for POST requests #5 
- [x] Implement pagination support #4
- [x] Implement token expiration #12
